image: python:3.10.1

pages:
  script:
    - pip install mkdocs
    - pip install mkdocs-material
    - pip install mkdocs-material-extensions
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main