image: python:3.10.1

before_script:
  - pip install -r requirements.txt

pages:
  script:
    - pip install mkdocs-material
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main