image: python:3.10.1

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install mkdocs-material-extensions

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main