site_name: Warung Pintar TechDocs
site_url: https://luphieanza.github.io/docs-as-code.github.io/
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - API: tutorials.md
    - About: about.md
theme:
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  font:
    text: Nunito Sans
    code: Open Sans
  favicon: img/Logo_AWP.svg
  logo: img/Logo_AWP.svg
  language: en
plugins:
  - search:
      lang: # 
        - en
        - id
copyright: Copyright &copy; 2017-2021 Warung Pintar Group
extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://example.com/
    - icon: fontawesome/brands/docker
      link: https://example.com/
    - icon: fontawesome/brands/linkedin
      link: https://example.com/
    - icon: fontawesome/brands/instagram
      link: https://example.com/
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css